define l2tpns::custom_config ( 
  String $account_all_origin                  = $::l2tpns::account_all_origin,
  String $accounting_dir                      = $::l2tpns::accounting_dir,
  String $allow_duplicate_users               = $::l2tpns::allow_duplicate_users,
  String $auth_tunnel_change_addr_src         = $::l2tpns::auth_tunnel_change_addr_src,
  String $bind_address,
  String $bind_address_remotelns              = $::l2tpns::bind_address_remotelns,
  String $bind_multi_address                  = $::l2tpns::bind_multi_address,
  Integer[0, 65535] $bind_portremotelns       = $::l2tpns::bind_portremotelns,
  String $cli_bind_address                    = $::l2tpns::cli_bind_address,
  Optional[String] $cluster_address           = $::l2tpns::cluster_address,
  Integer[0, 65535] $cluster_hb_interval      = $::l2tpns::cluster_hb_interval,
  Integer[0, 65535] $cluster_hb_timeout       = $::l2tpns::cluster_hb_timeout,
  Optional[String] $cluster_interface         = $::l2tpns::cluster_interface,
  Integer[0, 65535] $cluster_master_min_adv   = $::l2tpns::cluster_master_min_adv,
  Integer[0, 65535] $cluster_mcast_ttl        = $::l2tpns::cluster_mcast_ttl,
  Stdlib::Absolutepath $config_file,
  String $config_file_template                = 'l2tpns/startup-config.erb',
  Integer $debug                              = $::l2tpns::debug,
  Optional[String] $default_ipv6_domain_listi = $::l2tpns::default_ipv6_domain_listi,
  Integer[0, 65535] $dhcp6_preferred_lifetime = $::l2tpns::dhcp6_preferred_lifetime,
  Integer[0, 65535] $dhcp6_server_duid        = $::l2tpns::dhcp6_server_duid,
  Integer[0, 65535] $dhcp6_valid_lifetime     = $::l2tpns::dhcp6_valid_lifetime,
  String $disable_lac_func                    = $::l2tpns::disable_lac_func,
  String $disable_no_spoof                    = $::l2tpns::disable_no_spoof,
  String $disable_sending_hello               = $::l2tpns::disable_sending_hello,
  Integer[0, 65535] $dns6_lifetime            = $::l2tpns::dns6_lifetime,
  String $dump_speed                          = $::l2tpns::dump_speed,
  Integer[0, 65535] $echo_timeout             = $::l2tpns::echo_timeout,
  Optional[String] $guest_account             = $::l2tpns::guest_account,
  Optional[String] $hostname                  = $::l2tpns::hostname,
  Integer[0, 65535] $icmp_rate                = $::l2tpns::icmp_rate,
  Integer[0, 65535] $idle_echo_timeout        = $::l2tpns::idle_echo_timeout,
  String $iftun_address                       = $::l2tpns::iftun_address,
  String $ipv6_prefix                         = $::l2tpns::ipv6_prefix,
  String $kill_timedout_sessions              = $::l2tpns::kill_timedout_sessions,
  Integer[0, 65535] $l2tp_mtu                 = $::l2tpns::l2tp_mtu,
  Integer[0, 65535] $l2tp_port,
  String $l2tp_secret                         = $::l2tpns::l2tp_secret,
  String $lock_pages                          = $::l2tpns::lock_pages,
  String $log_file,
  String $multi_hostname                      = $::l2tpns::multi_hostname,
  Integer $multi_read_count                   = $::l2tpns::multi_read_count,
  String $nexthop6_address                    = $::l2tpns::nexthop6_address,
  String $nexthop_address                     = $::l2tpns::nexthop_address,
  String $no_throttle_local_IP                = $::l2tpns::no_throttle_local_IP,
  Integer[0, 65535] $nsctl_port,
  Integer[0, 65535] $packet_limit             = $::l2tpns::packet_limit,
  String $peer_address                        = $::l2tpns::peer_address,
  String $pid_file              = $::l2tpns::pid_file,
  String $ppp_keepalive                       = $::l2tpns::ppp_keepalive ,
  Integer[0, 65535] $ppp_max_configure        = $::l2tpns::ppp_max_configure,
  Integer[0, 65535] $ppp_max_failure          = $::l2tpns::ppp_max_failure,
  String $pppoe_ac_name                       = $::l2tpns::pppoe_ac_name,
  String $pppoe_if_to_bind                    = $::l2tpns::pppoe_if_to_bind,
  String $pppoe_only_equal_svc_name           = $::l2tpns::pppoe_only_equal_svc_name,
  String $pppoe_service_name                  = $::l2tpns::pppoe_service_name,
  Integer[0, 65535] $ppp_restart_time         = $::l2tpns::ppp_restart_time,
  String $primary_dns                         = $::l2tpns::primary_dns,
  String $primary_ipv6_dns                    = $::l2tpns::primary_ipv6_dns,
  String $primary_radius                      = $::l2tpns::primary_radius,
  Integer[0, 65535] $primary_radius_port      = $::l2tpns::primary_radius_port,
  String $radius_accounting                   = $::l2tpns::radius_accounting,
  String $radius_authtypes                    = $::l2tpns::radius_authtypes,
  Integer[0, 65535] $radius_bind_max          = $::l2tpns::radius_bind_max,
  Integer[0, 65535] $radius_bind_min          = $::l2tpns::radius_bind_min,
  Integer[0, 65535] $radius_dae_port          = $::l2tpns::radius_dae_port,
  Integer[0, 65535] $radius_interim           = $::l2tpns::radius_interim,
  Integer $radius_nas_offset,
  String $radius_secret                       = $::l2tpns::radius_secret,
  String $random_device                       = $::l2tpns::random_device,
  String $scheduler_fifo                      = $::l2tpns::scheduler_fifo,
  String $secondary_dns                       = $::l2tpns::secondary_dns,
  String $secondary_ipv6_dns                  = $::l2tpns::secondary_ipv6_dns,
  String $secondary_radius                    = $::l2tpns::secondary_radius,
  Integer[0, 65535] $secondary_radius_port    = $::l2tpns::secondary_radius_port,
  String $send_garp                           = $::l2tpns::send_garp,
  Integer $throttle_buckets                   = $::l2tpns::throttle_buckets,
  Integer[0, 65535] $throttle_speed           = $::l2tpns::throttle_speed,
  Optional[String] $tundevicename             = $::l2tpns::tundevicename,
  Array[String] $load_plugins                 = $::l2tpns::load_plugins,
  String $handle_out_of_seq                   = $::l2tpns::handle_out_of_seq,
 
) {

  if ! defined(Class['l2tpns']) {
    fail('You must include the l2tpns base class before using any l2tpns defined resources')
  } 
  
  file { $config_file:
    ensure  => file,
    content => template($config_file_template),
  } 
} 
