class l2tpns (
  String $account_all_origin,
  String $accounting_dir,
  String $allow_duplicate_users,
  String $auth_tunnel_change_addr_src,
  String $bind_address,
  String $bind_address_remotelns,
  String $bind_multi_address,
  Integer[0, 65535] $bind_portremotelns,
  String $cli_bind_address,
  Optional[String] $cluster_address,
  Integer[0, 65535] $cluster_hb_interval,
  Integer[0, 65535] $cluster_hb_timeout,
  Optional[String] $cluster_interface,
  Integer[0, 65535] $cluster_master_min_adv,
  Integer[0, 65535] $cluster_mcast_ttl,
  Stdlib::Absolutepath $config_file,
  String $config_file_template,
  Optional[Integer[0, 65535]] $core_id,
  Integer $debug,
  Optional[String] $default_ipv6_domain_list ,
  Integer[0, 65535] $dhcp6_preferred_lifetime,
  Integer[0, 65535] $dhcp6_server_duid,
  Integer[0, 65535] $dhcp6_valid_lifetime,
  String $disable_lac_func ,
  String $disable_no_spoof ,
  String $disable_sending_hello ,
  Integer[0, 65535] $dns6_lifetime ,
  String $dump_speed ,
  Integer[0, 65535] $echo_timeout ,
  Optional[String] $guest_account ,
  Optional[String] $hostname,
  Integer[0, 65535] $icmp_rate,
  Integer[0, 65535] $idle_echo_timeout ,
  String $iftun_address ,
  Stdlib::Absolutepath $init_script_file,
  String $init_script_template,
  String $ipv6_prefix,
  String $kill_timedout_sessions ,
  Integer[0, 65535] $l2tp_mtu ,
  Integer[0, 65535] $l2tp_port,
  String $l2tp_secret,
  String $lock_pages,
  Stdlib::Absolutepath $log_file,
  String $multi_hostname,
  Integer $multi_read_count,
  String $nexthop6_address,
  String $nexthop_address,
  String $no_throttle_local_IP,
  Integer[0, 65535] $nsctl_port,
  String $package_ensure,
  Boolean $package_manage,
  String $package_name,
  Array[String] $package_require,
  Integer[0, 65535] $packet_limit,
  String $peer_address,
  Stdlib::Absolutepath $pid_file,
  String $ppp_keepalive,
  Integer[0, 65535] $ppp_max_configure,
  Integer[0, 65535] $ppp_max_failure,
  String $pppoe_ac_name,
  String $pppoe_if_to_bind ,
  String $pppoe_only_equal_svc_name,
  String $pppoe_service_name,
  Integer[0, 65535] $ppp_restart_time,
  String $primary_dns,
  String $primary_ipv6_dns,
  String $primary_radius,
  Integer[0, 65535] $primary_radius_port,
  String $radius_accounting,
  String $radius_authtypes,
  Integer[0, 65535] $radius_bind_max,
  Integer[0, 65535] $radius_bind_min,
  Integer[0, 65535] $radius_dae_port,
  Integer[0, 65535] $radius_interim,
  Integer[0, 65535] $radius_nas_offset,
  String $radius_secret,
  String $random_device,
  String $scheduler_fifo,
  String $secondary_dns,
  String $secondary_ipv6_dns,
  String $secondary_radius,
  Integer[0, 65535] $secondary_radius_port,
  String $send_garp,
  Boolean $service_enable,
  String $service_ensure,
  String $service_name,
  Stdlib::Absolutepath $subsys_file,
  Integer[0, 65535] $telnet_port,
  Integer $throttle_buckets,
  Integer[0, 65535] $throttle_speed,
  Optional[String] $tundevicename,
  Array[String] $load_plugins,
  Optional[Hash] $repo,
  String $handle_out_of_seq,
) {
  contain l2tpns::repo
  contain l2tpns::install
  contain l2tpns::init_script
  contain l2tpns::config
  contain l2tpns::service

  Class['::l2tpns::repo']        ->
  Class['::l2tpns::install']     ->
  Class['::l2tpns::init_script'] ->
  Class['::l2tpns::config']      ~>
  Class['::l2tpns::service'] 
}
